package com.common;

public enum TaskQueue {
  PAYMENT_FULFILLMENT_WORKFLOW_TASK_QUEUE,
  INVENTORY_ACTIVITY_TASK_QUEUE,
  SHIPPING_ACTIVITY_TASK_QUEUE,
  ORDER_ACTIVITY_TASK_QUEUE,
  CART_ACTIVITY_TASK_QUERY
}
